### ISSUE TITLE
SparkStreaming读取Kafka数据时抛出jaas.conf文件不存在的错误

### ISSUE THREAD

**Issue by sunspeedzy** [fayson/cdhproject#15]
您好

我用spark-submit以yarn client的方式提交SparkStreaming应用读取启用了Kerberos认证的kafka数据时，如果Kafka Topic有数据产生，SparkStreaming应用就会抛出
java.io.IOException: /home/aspire/kerberos/jaas.conf (没有这样的文件或目录)
而我在CDH集群的每个节点的这个路径下都放置了这个文件，并且在读取Kafka之前用这个路径下的jaas.conf连接ZooKeeper是正常的。

还请您帮我解答疑问

**我的提交命令是**
spark2-submit --master yarn --deploy-mode client \\
 --class com.zy.KrbKafkaStreaming  --num-executors 2 \\
 --executor-memory 4G --executor-cores 2 \\
 --conf spark.core.connection.ack.wait.timeout=300 \\
 --conf spark.executor.memoryOverhead=1024 \\
 --conf spark.memory.storageFraction=0.4 \\
 --conf "spark.driver.extraJavaOptions=-Djava.security.auth.login.config=/home/aspire/kerberos/jaas.conf" \\
 --conf "spark.executor.extraJavaOptions=-Djava.security.auth.login.config=/home/aspire/kerberos/jaas.conf" \\
 /home/aspire/zhangyan/streamsimu/sparktrain-ch12-1.0.jar 

**错误是这样的**
19/11/06 17:44:20 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 2.0 (TID 6, node-62, executor 1): org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:789)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:608)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:589)
        at org.apache.spark.streaming.kafka010.CachedKafkaConsumer.<init>(CachedKafkaConsumer.scala:45)
        at org.apache.spark.streaming.kafka010.CachedKafkaConsumer$.get(CachedKafkaConsumer.scala:194)
        at org.apache.spark.streaming.kafka010.KafkaRDDIterator.<init>(KafkaRDD.scala:252)
        at org.apache.spark.streaming.kafka010.KafkaRDD.compute(KafkaRDD.scala:212)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.SecurityException: java.io.IOException: /home/aspire/kerberos/jaas.conf (没有这样的文件或目录)
        at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
        at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at javax.security.auth.login.Configuration$2.run(Configuration.java:255)
        at javax.security.auth.login.Configuration$2.run(Configuration.java:247)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246)
        at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:112)
        at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:96)
        at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:78)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:103)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:61)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:86)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:710)
        ... 17 more
Caused by: java.io.IOException: /home/aspire/kerberos/jaas.conf (没有这样的文件或目录)
        at sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:666)
        at sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:262)
        at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:135)
        ... 34 more

谢谢

**Comment by sunspeedzy** [comment]
补充一下，在spark-submit中添加下行还是报这样的错误
--files "/home/aspire/kerberos/jaas.conf#jaas.conf" \

**Comment by sunspeedzy** [comment]
以yarn cluster方式提交的话
Driver端和Executor端的security配置应该是 java.security.auth.login.config=./jaas.conf
yarn client 方式应该也是如此，或者只是Executor端这么配置
